// Code generated by thriftgo (0.3.15). DO NOT EDIT.

package errno

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
)

var (
	Success = &ErrNo{
		ErrCode: int64(Err_Success),
		ErrMsg:  "success",
	}

	NoRoute = &ErrNo{
		ErrCode: int64(Err_NoRoute),
		ErrMsg:  "no route",
	}

	NoMethod = &ErrNo{
		ErrCode: int64(Err_NoMethod),
		ErrMsg:  "no method",
	}

	BadRequest = &ErrNo{
		ErrCode: int64(Err_BadRequest),
		ErrMsg:  "bad request",
	}

	ParamsErr = &ErrNo{
		ErrCode: int64(Err_ParamsErr),
		ErrMsg:  "params error",
	}

	AuthorizeFail = &ErrNo{
		ErrCode: int64(Err_AuthorizeFail),
		ErrMsg:  "authorize failed",
	}

	TooManyRequest = &ErrNo{
		ErrCode: int64(Err_TooManyRequest),
		ErrMsg:  "too many requests",
	}

	ServiceErr = &ErrNo{
		ErrCode: int64(Err_ServiceErr),
		ErrMsg:  "service error",
	}

	RPCUserSrvErr = &ErrNo{
		ErrCode: int64(Err_RPCUserSrvErr),
		ErrMsg:  "rpc user service error",
	}

	UserSrvErr = &ErrNo{
		ErrCode: int64(Err_UserSrvErr),
		ErrMsg:  "user service error",
	}

	RPCUserAdminSrvErr = &ErrNo{
		ErrCode: int64(Err_RPCUserAdminSrvErr),
		ErrMsg:  "rpc system service error",
	}

	UserAdminSrvErr = &ErrNo{
		ErrCode: int64(Err_UserAdminSrvErr),
		ErrMsg:  "system service error",
	}

	RPCProductSrvErr = &ErrNo{
		ErrCode: int64(Err_RPCProductSrvErr),
		ErrMsg:  "rpc car service error",
	}

	ProductSrvErr = &ErrNo{
		ErrCode: int64(Err_ProductSrvErr),
		ErrMsg:  "car service error",
	}

	RPCOrderSrvErr = &ErrNo{
		ErrCode: int64(Err_RPCOrderSrvErr),
		ErrMsg:  "rpc profile service error",
	}

	OrderSrvErr = &ErrNo{
		ErrCode: int64(Err_OrderSrvErr),
		ErrMsg:  "profile service error",
	}

	RPCActivitySrvErr = &ErrNo{
		ErrCode: int64(Err_RPCActivitySrvErr),
		ErrMsg:  "rpc trip service error",
	}

	ActivitySrvErr = &ErrNo{
		ErrCode: int64(Err_ActivitySrvErr),
		ErrMsg:  "trip service error",
	}

	RPCCartSrvErr = &ErrNo{
		ErrCode: int64(Err_RPCCartSrvErr),
		ErrMsg:  "rpc trip service error",
	}

	CartSrvErr = &ErrNo{
		ErrCode: int64(Err_CartSrvErr),
		ErrMsg:  "trip service error",
	}

	RecordNotFound = &ErrNo{
		ErrCode: int64(Err_RecordNotFound),
		ErrMsg:  "record not found",
	}

	RecordAlreadyExist = &ErrNo{
		ErrCode: int64(Err_RecordAlreadyExist),
		ErrMsg:  "record already exist",
	}

	DirtyData = &ErrNo{
		ErrCode: int64(Err_DirtyData),
		ErrMsg:  "dirty data",
	}
)

type Err int64

const (
	Err_Success            Err = 200
	Err_NoRoute            Err = 405
	Err_NoMethod           Err = 404
	Err_BadRequest         Err = 500
	Err_ParamsErr          Err = 504
	Err_AuthorizeFail      Err = 403
	Err_TooManyRequest     Err = 429
	Err_ServiceErr         Err = 502
	Err_RecordNotFound     Err = 1000
	Err_RecordAlreadyExist Err = 1010
	Err_DirtyData          Err = 1020
	Err_RPCUserSrvErr      Err = 30001
	Err_RPCUserAdminSrvErr Err = 30002
	Err_RPCOrderSrvErr     Err = 30003
	Err_RPCProductSrvErr   Err = 30004
	Err_RPCActivitySrvErr  Err = 30005
	Err_RPCCartSrvErr      Err = 30006
	Err_UserSrvErr         Err = 40001
	Err_UserAdminSrvErr    Err = 40002
	Err_OrderSrvErr        Err = 40003
	Err_ProductSrvErr      Err = 40004
	Err_ActivitySrvErr     Err = 40005
	Err_CartSrvErr         Err = 40006
)

func (p Err) String() string {
	switch p {
	case Err_Success:
		return "Success"
	case Err_NoRoute:
		return "NoRoute"
	case Err_NoMethod:
		return "NoMethod"
	case Err_BadRequest:
		return "BadRequest"
	case Err_ParamsErr:
		return "ParamsErr"
	case Err_AuthorizeFail:
		return "AuthorizeFail"
	case Err_TooManyRequest:
		return "TooManyRequest"
	case Err_ServiceErr:
		return "ServiceErr"
	case Err_RecordNotFound:
		return "RecordNotFound"
	case Err_RecordAlreadyExist:
		return "RecordAlreadyExist"
	case Err_DirtyData:
		return "DirtyData"
	case Err_RPCUserSrvErr:
		return "RPCUserSrvErr"
	case Err_RPCUserAdminSrvErr:
		return "RPCUserAdminSrvErr"
	case Err_RPCOrderSrvErr:
		return "RPCOrderSrvErr"
	case Err_RPCProductSrvErr:
		return "RPCProductSrvErr"
	case Err_RPCActivitySrvErr:
		return "RPCActivitySrvErr"
	case Err_RPCCartSrvErr:
		return "RPCCartSrvErr"
	case Err_UserSrvErr:
		return "UserSrvErr"
	case Err_UserAdminSrvErr:
		return "UserAdminSrvErr"
	case Err_OrderSrvErr:
		return "OrderSrvErr"
	case Err_ProductSrvErr:
		return "ProductSrvErr"
	case Err_ActivitySrvErr:
		return "ActivitySrvErr"
	case Err_CartSrvErr:
		return "CartSrvErr"
	}
	return "<UNSET>"
}

func ErrFromString(s string) (Err, error) {
	switch s {
	case "Success":
		return Err_Success, nil
	case "NoRoute":
		return Err_NoRoute, nil
	case "NoMethod":
		return Err_NoMethod, nil
	case "BadRequest":
		return Err_BadRequest, nil
	case "ParamsErr":
		return Err_ParamsErr, nil
	case "AuthorizeFail":
		return Err_AuthorizeFail, nil
	case "TooManyRequest":
		return Err_TooManyRequest, nil
	case "ServiceErr":
		return Err_ServiceErr, nil
	case "RecordNotFound":
		return Err_RecordNotFound, nil
	case "RecordAlreadyExist":
		return Err_RecordAlreadyExist, nil
	case "DirtyData":
		return Err_DirtyData, nil
	case "RPCUserSrvErr":
		return Err_RPCUserSrvErr, nil
	case "RPCUserAdminSrvErr":
		return Err_RPCUserAdminSrvErr, nil
	case "RPCOrderSrvErr":
		return Err_RPCOrderSrvErr, nil
	case "RPCProductSrvErr":
		return Err_RPCProductSrvErr, nil
	case "RPCActivitySrvErr":
		return Err_RPCActivitySrvErr, nil
	case "RPCCartSrvErr":
		return Err_RPCCartSrvErr, nil
	case "UserSrvErr":
		return Err_UserSrvErr, nil
	case "UserAdminSrvErr":
		return Err_UserAdminSrvErr, nil
	case "OrderSrvErr":
		return Err_OrderSrvErr, nil
	case "ProductSrvErr":
		return Err_ProductSrvErr, nil
	case "ActivitySrvErr":
		return Err_ActivitySrvErr, nil
	case "CartSrvErr":
		return Err_CartSrvErr, nil
	}
	return Err(0), fmt.Errorf("not a valid Err string")
}

func ErrPtr(v Err) *Err { return &v }
func (p *Err) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = Err(result.Int64)
	return
}

func (p *Err) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type ErrNo struct {
	ErrCode int64  `thrift:"ErrCode,1" form:"ErrCode" json:"ErrCode" query:"ErrCode"`
	ErrMsg  string `thrift:"ErrMsg,2" form:"ErrMsg" json:"ErrMsg" query:"ErrMsg"`
}

func NewErrNo() *ErrNo {
	return &ErrNo{}
}

func (p *ErrNo) InitDefault() {
}

func (p *ErrNo) GetErrCode() (v int64) {
	return p.ErrCode
}

func (p *ErrNo) GetErrMsg() (v string) {
	return p.ErrMsg
}

var fieldIDToName_ErrNo = map[int16]string{
	1: "ErrCode",
	2: "ErrMsg",
}

func (p *ErrNo) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_ErrNo[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *ErrNo) ReadField1(iprot thrift.TProtocol) error {

	var _field int64
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		_field = v
	}
	p.ErrCode = _field
	return nil
}
func (p *ErrNo) ReadField2(iprot thrift.TProtocol) error {

	var _field string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = v
	}
	p.ErrMsg = _field
	return nil
}

func (p *ErrNo) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("ErrNo"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *ErrNo) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("ErrCode", thrift.I64, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI64(p.ErrCode); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *ErrNo) writeField2(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("ErrMsg", thrift.STRING, 2); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.ErrMsg); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *ErrNo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ErrNo(%+v)", *p)

}

type Response struct {
	Code    int64  `thrift:"Code,1" form:"Code" json:"Code" query:"Code"`
	Message string `thrift:"Message,2" form:"Message" json:"Message" query:"Message"`
	Data    []byte `thrift:"Data,3" form:"Data" json:"Data" query:"Data"`
}

func NewResponse() *Response {
	return &Response{}
}

func (p *Response) InitDefault() {
}

func (p *Response) GetCode() (v int64) {
	return p.Code
}

func (p *Response) GetMessage() (v string) {
	return p.Message
}

func (p *Response) GetData() (v []byte) {
	return p.Data
}

var fieldIDToName_Response = map[int16]string{
	1: "Code",
	2: "Message",
	3: "Data",
}

func (p *Response) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 3:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField3(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_Response[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *Response) ReadField1(iprot thrift.TProtocol) error {

	var _field int64
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		_field = v
	}
	p.Code = _field
	return nil
}
func (p *Response) ReadField2(iprot thrift.TProtocol) error {

	var _field string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = v
	}
	p.Message = _field
	return nil
}
func (p *Response) ReadField3(iprot thrift.TProtocol) error {

	var _field []byte
	if v, err := iprot.ReadBinary(); err != nil {
		return err
	} else {
		_field = []byte(v)
	}
	p.Data = _field
	return nil
}

func (p *Response) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("Response"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
		if err = p.writeField3(oprot); err != nil {
			fieldId = 3
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *Response) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("Code", thrift.I64, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI64(p.Code); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *Response) writeField2(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("Message", thrift.STRING, 2); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.Message); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *Response) writeField3(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("Data", thrift.STRING, 3); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteBinary([]byte(p.Data)); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 end error: ", p), err)
}

func (p *Response) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Response(%+v)", *p)

}
